apiVersion: batch/v1
kind: Job
metadata:
  name: tf-resnet50-imagenet
spec:
  template:
    metadata:
      name: tf-resnet50-imagenet
    spec:
      containers:
      - name: tf-resnet50-imagenet
        image: esparig/tf-resnet50-imagenet:latest
        command: ["/bin/bash","-c",
        "python3 $IMAGE_CLASSIFICATION/train.py \
        --experiment=resnet_imagenet \
        --config_file=$EXPERIMENT/imagenet_resnet50_gpu_custom.yaml \
        --mode=train_and_eval \
        --model_dir=$MODEL_DIR \
        --params_override='runtime.num_gpus=1'"]
        volumeMounts:
        - name: data-volume
          mountPath: /data
      nodeSelector:
        kubernetes.io/hostname: vnode-1.localdomain

      volumes:
      - name: data-volume
        hostPath:
          path: /disk2/data
      
      restartPolicy: Never
