apiVersion: batch/v1
kind: Job
metadata:
  name: testing-tf-models
spec:
  backoffLimit: 2
  template:
    metadata:
      name: testing-tf-models
    spec:
      containers:
      - name: tf-gpu-models
        image: esparig/testing-tf-models:latest
        command: ["/bin/bash","-c","cd /usr/local/lib/python3.6/dist-packages/official && python3 vision/image_classification/mnist_main.py --model_dir=$MODEL_DIR --data_dir=$DATA_DIR --train_epochs=20 --download"]
      restartPolicy: Never
