apiVersion: batch/v1
kind: Job
metadata:
  name: tf-models-resnet50
spec:
  backoffLimit: 2
  template:
    metadata:
      name: tf-models-resnet50
    spec:
      containers:
      - name: tf-gpu-models
        image: esparig/testing-tf-models:latest
        command: ["/bin/bash","-c",
        "cd /usr/local/lib/python3.6/dist-packages/official && \
        python3 vision/image_classification/classifier_trainer.py \
        --mode=train_and_eval \
        --model_type=resnet \
        --dataset=imagenet \
        --model_dir=$MODEL_DIR \
        --data_dir=$DATA_DIR \
        --config_file=configs/examples/resnet/imagenet/gpu.yaml \
        --params_override='runtime.num_gpus=$NUM_GPUS'"]
      restartPolicy: Never
