apiVersion: batch/v1
kind: Job
metadata:
  name: ls-data
spec:
  template:
    metadata:
      name: ls-data
    spec:
      containers:
      - name: tf-resnet50-imagenet
        image: esparig/tf-resnet50-imagenet:latest
        command: ["/bin/bash","-c",
        "ls /data"]
        volumeMounts:
        - name: data-volume
          mountPath: /data
        resources:
          limits:
            memory: "5Gi"
            cpu: "3"
      nodeSelector:
        kubernetes.io/hostname: vnode-1.localdomain

      volumes:
      - name: data-volume
        hostPath:
          path: /disk2/data
      
      restartPolicy: Never
