apiVersion: batch/v1
kind: Job
metadata:
  name: simple-mnist
spec:
  backoffLimit: 2
  template:
    metadata:
      name: simple-mnist
    spec:
      containers:
      - name: tf-gpu-simple-mnist
        image: esparig/simple-mnist:latest
        command:
         - "python3"
         - "/opt/test-gpu-training/simple-mnist.py"
      restartPolicy: Never
