kind: Job
apiVersion: batch/v1
metadata:
  name: simple-mnist
spec:
  template:
    spec:
      containers:
      - name: countdown
        image: bash
        command: ["/bin/sh",  "-c"]
        args:
          - for i in 9 8 7 6 5 4 3 2 1 ; do echo $i >> /tmp/out; done &&
            echo Done!
        volumeMounts:
          - name: my-nfs-volume
            mountPath: /mnt/nfs_share          
      restartPolicy: OnFailure
      volumes:
      - name: example-pv
        persistentVolumeClaim:
          claimName: example-local-claim
