# Dockerfile to create a container for training a small network for MNIST
# recognition using Tensorflow
#
# 20210507 - Estibaliz Parcero

FROM tensorflow/tensorflow:latest-gpu

COPY scripts/simple-mnist.py /opt/test-gpu-training/simple-mnist.py
