# Dockerfile to create a container for training Denoising images
# https://github.com/esparig/deep-learning-nanodegree/tree/master/autoencoder/denoising-autoencoder
#
# 20221021 - Estibaliz Parcero

# From https://github.com/pytorch/pytorch
FROM pytorch/pytorch:latest

COPY  denoising.py .
