name: Docker Image CI Prostate Cancer

on:
  push:
    paths:
    - 'dockerfiles/lafe-prostatecancer/**'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: esparig/tf-prostatecancer
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: dockerfiles/lafe-prostatecancer/Dockerfile
        context: dockerfiles/lafe-prostatecancer/
