name: Docker Image CI Pytorch Denoising

on:
  push:
    paths:
    - 'dockerfiles/pytorch-denoising/**'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: esparig/Pytorch-Denoising
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: dockerfiles/pytorch-denoising/Dockerfile
        context: dockerfiles/pytorch-denoising/
