name: Docker Image CI Resnet50 Imagenet

on:
  push:
    paths:
    - 'dockerfiles/tf-resnet50/**'

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: esparig/TF-Resnet50-Imagenet
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: dockerfiles/tf-resnet50/Dockerfile
        context: dockerfiles/tf-resnet50/
